### ISSUE TITLE
Users can't easily infer the language of unfamilair good morning phrases.

### ISSUE THREAD

**Issue by Mori935** [coillteoir/MorningBot#16]
Being able to code it to see the origin flag of each good morning message.

For example a "guten morgen" reacts with the sunshine aswell as reacting with the language origin flag being Germany

For countries that all use the same language try to find the country of Origin for example, Spain, Mexico, and South America (Minus Brazil) their origin country would be Spain so to react with the Spanish flag.

There is currently no way for a user to know what language is being used without prior knowledge or google

**Comment by coillteoir** [comment]
I like this idea, could be a good way to make people feel included. Although it's important to consider geopolitical issues I think this is valuable!

**Comment by coillteoir** [comment]
I think reactions are overkill in this scenario. I think a good start to addressing this would be adding supported languages to the readme with the phrases and their language of origin.
