### ISSUE TITLE
Leaderboard graphs

### ISSUE THREAD

**Issue by aidan-mcphee** [coillteoir/MorningBot#36]
**Is your feature request related to a problem? Please describe.**

The current problem is as the leaderboard exponentially grows there won't be enough space for all the users

**Describe the solution you'd like**

Using a grpahing library in python convert the leaderboard to a graph image and add it to the embed in place of text fields

**Describe alternatives you've considered**

simply limiting the amount of entries on the leaderboard, I don't like this option as it doesn't show the amount of people
on the leaderboard

**Comment by coillteoir** [comment]
Limiting the amount of members means that the embed won't grow too large. 
I don't see how a graph would solve this, as you'd still need to display the names of users on the leaderboard.
