### ISSUE TITLE
On Discord Mobile, reaction appears then disappears

### ISSUE THREAD

**Issue by RJMurg** [coillteoir/MorningBot#48]
**Describe the bug**
During the morning period, using any MorningBot morning phrase on Discord Mobile (tested on iOS) will cause the reaction to appear and disappear immediately to the user. An app restart will fix this display behaviour. The reaction is present, just invisible to the user until they restart the app.

**To Reproduce**
1. Open the Discord Mobile App (Might just be iOS).
2. During the relevant morning period, use a good morning phrase,
3. Watch the reaction appear and disappear.

**Expected behavior**
The reaction should appear and remain there.

**Screenshots**
No screenshots of the problem, though screenshots of others experiencing the same issue:
![image](https://github.com/coillteoir/MorningBot/assets/115182656/32a54bb5-8f3d-412f-ab82-a261a1f0b3b8)
![image](https://github.com/coillteoir/MorningBot/assets/115182656/4a37d2f9-39ea-4b2b-a003-60e0d72aec51)
![image](https://github.com/coillteoir/MorningBot/assets/115182656/ed263a72-86e8-4de5-b6e1-9d7bd5020a95)

**Smartphone (please complete the following information):**
 - Device: iPhone 14 Pro
 - OS: iOS 17.4
 - Browser N/A
 - Version N/A

**Additional context**
- Discord App Version: 216.0
- JS Build: 55376
Present on previous Discord app builds

**Comment by RJMurg** [comment]
My suspicion is that it is probably some weird race condition with the message being sent and synced and MB replying before the mobile app receives confirmation that the message has been sent.

Solution could be adding a short delay between detecting the message, and MB replying.

**Comment by dublinsubway** [comment]
Happens on Android as well, not specifically iOS problem:

**Smartphone (please complete the following information):**

Device: Cubot P40
OS: Android 10

**Additional context**

Discord App Version: 216.14
JS Build: 21601400151168

**Comment by coillteoir** [comment]
I think this is an upstream issue and isn't caused by the bot. 

It's probably a race condition on discord's servers, and it's minor enough that a fix isn't necessary.
I haven't had time to troubleshoot since I'm busy with other things, but it's good to be aware of this.

I will welcome a fix, if one is sent in, though.
