### ISSUE TITLE
Add a linebreak between leaderboard announcement and #1 spot on the leaderboard

### ISSUE THREAD

**Issue by dofloinn** [coillteoir/MorningBot#51]
There is no linebreak between leaderboard announcement and #1 spot on the leaderboard

![](https://i.imgur.com/JaRhuPK.png)

It's together and looks bad

**Comment by coillteoir** [comment]
This is already in #32 it just needs to be merged/run on your infrastructure!

**Comment by RJMurg** [comment]
Submit a Sysadmin ticket for it to be deployed.

**Comment by dofloinn** [comment]
slay

**Comment by coillteoir** [comment]
> Submit a Sysadmin ticket for it to be deployed.
Not a morning bot issue consider this conversation LOCKED
