### ISSUE TITLE
Use a .env

### ISSUE THREAD

**Issue by RJMurg** [coillteoir/MorningBot#52]
**Is your feature request related to a problem? Please describe.**
Doing a 'git pull' to pull upstream changes requires a stash as the APIs are stored in the config, which is a tracked file in git. This makes it more difficult to update.

**Describe the solution you'd like**
Put the Bot Token, and the API Keys in a .env

**Describe alternatives you've considered**
Not doing that. It just means you have to keep the API keys in an notepad temporarily until you pull the update

**Comment by coillteoir** [comment]
good idea!

**Comment by RJMurg** [comment]
Also put the channel id!

**Comment by coillteoir** [comment]
Maybe take a look at this issue #31
