### ISSUE TITLE
Bot is building image with files that should be excluded

### ISSUE THREAD

**Issue by RJMurg** [coillteoir/MorningBot#54]
**Describe the bug**
While looking at the filesystem of the container for debugging reasons, I noticed that files which were marked in the .dockerignore file were actually being copied into the container and built with it. This includes the .git, README.md, CONTRIBUTING.md, etc.

**To Reproduce**
1. Run the container
2. Attach to the container or copy out its contents
3. Navigate to '/workspace/MorningBot'
4. Type `ls -la`

**Expected behavior**
Files in the .dockerignore should not be built into the container

**Desktop (please complete the following information):**
 - Ubuntu Server 22.04

**Comment by coillteoir** [comment]
The image you're running is outdated, probably. Current implementations in #53 only copy what is necessary for the bot to run, I'd recommend pruning your images, and rebuilding using `docker compose build`.
